import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "./components/Card";
import { SAMPLE_DATA } from "./components/Card/constant";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ponyo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Logo.svg" />
      </Head>

      <main className={styles.main}>
        {/* <Carousel slides={SAMPLE_IMAGE} /> */}
      </main>
      <footer></footer>
    </div>
  );
}

export default Home;
