export const MY_INTEREST = [
  {
    name: "Burger",
    description: "Scrumtious",
    price: "100-200",
    location: "Yummy Tummy",
    cover:
      "https://brandinside.asia/wp-content/uploads/2019/07/shutterstock_1437332618-e1563988304801.jpg",
    rate: "4.00",
    status: "open",
    liked: true,
    saved: true,
  },
  {
    name: "Grimm",
    description: "Food fron hell",
    price: "10-20",
    location: "Hell",
    cover: "https://pbs.twimg.com/media/DIY_wusWsAITtlZ.jpg",
    rate: "0.02",
    status: "open",
    liked: false,
    saved: true,
  },
  {
    name: "Chef Choice",
    description: "Kid Mai Ork",
    price: "123-456",
    location: "Random",
    cover:
      "https://10play.com.au/ip/s3/2019/06/15/e3e0563683d18bf7646d859fa3c8f43a-435980.jpg?image-profile=gallery",
    rate: "4.23",
    status: "close",
    liked: false,
    saved: true,
  },
  {
    name: "Buttiro",
    description: "Warm chunky wrap",
    price: "123-456",
    location: "Random",
    cover:
      "https://www.onceuponachef.com/images/2018/03/Breakfast-Burritos.jpg",
    rate: "4.23",
    status: "close",
    liked: false,
    saved: true,
  },
  {
    name: "Healthy Camp",
    description: "Sweet and sour. Freshhhh",
    price: "123-456",
    location: "Random",
    cover:
      "https://data.thefeedfeed.com/static/2019/07/24/15639952655d38ac8125af7.png",
    rate: "4.23",
    status: "close",
    liked: false,
    saved: true,
  },
  {
    name: "Food Art",
    description: "Heart warming",
    price: "123-456",
    location: "Random",
    cover: "https://insidethemagic.net/wp-content/uploads/2019/04/Up.jpg",
    rate: "4.23",
    status: "close",
    liked: false,
    saved: true,
  },
  {
    name: "Sabb",
    description: "Burn your tongue to hell",
    price: "123-456",
    location: "Random",
    cover:
      "http://cdn.cnn.com/cnnnext/dam/assets/151215114545-40-thai-food-27-som-tam-1.jpg",
    rate: "4.23",
    status: "close",
    liked: false,
    saved: true,
  },
  {
    name: "Tiny Food",
    description: "Smallest serving size you'll ever have",
    price: "123-456",
    location: "Random",
    cover:
      "https://static.onecms.io/wp-content/uploads/sites/14/2016/07/08/071216-tiny-food.png",
    rate: "4.23",
    status: "close",
    liked: false,
    saved: true,
  },
];
